extends Node
# Holds the sounds that get assigned to the phonemes
# Change this to preloads once the sounds are recorded.
var sound_lib : Dictionary[int,Variant] = {
	0 : preload("res://assets/audio/phoneme_sounds/phoneme-01.mp3"),
	1 : preload("res://assets/audio/phoneme_sounds/phoneme-02.mp3"),
	2 : preload("res://assets/audio/phoneme_sounds/phoneme-03.mp3"),
	3 : preload("res://assets/audio/phoneme_sounds/phoneme-04.mp3"),
	4 : preload("res://assets/audio/phoneme_sounds/phoneme-05.mp3"),
	5 : preload("res://assets/audio/phoneme_sounds/phoneme-06.mp3"),
	6 : preload("res://assets/audio/phoneme_sounds/phoneme-07.mp3"),
	7 : preload("res://assets/audio/phoneme_sounds/phoneme-08.mp3"),
	8 : preload("res://assets/audio/phoneme_sounds/phoneme-09.mp3"),
	9 : preload("res://assets/audio/phoneme_sounds/phoneme-10.mp3"),
	10 : preload("res://assets/audio/phoneme_sounds/phoneme-11.mp3"),
	11 : preload("res://assets/audio/phoneme_sounds/phoneme-12.mp3"),
	12 : preload("res://assets/audio/phoneme_sounds/phoneme-13.mp3"),
	13 : preload("res://assets/audio/phoneme_sounds/phoneme-14.mp3"),
	14 : preload("res://assets/audio/phoneme_sounds/phoneme-15.mp3"),
	15 : preload("res://assets/audio/phoneme_sounds/phoneme-16.mp3"),
	16 : preload("res://assets/audio/phoneme_sounds/phoneme-17.mp3"),
	17 : preload("res://assets/audio/phoneme_sounds/phoneme-18.mp3"),
	18 : preload("res://assets/audio/phoneme_sounds/phoneme-19.mp3"),
	19 : preload("res://assets/audio/phoneme_sounds/phoneme-20.mp3"),
	20 : preload("res://assets/audio/phoneme_sounds/phoneme-21.mp3"),
	21 : preload("res://assets/audio/phoneme_sounds/phoneme-22.mp3"),
	22 : preload("res://assets/audio/phoneme_sounds/phoneme-23.mp3"),
	23 : preload("res://assets/audio/phoneme_sounds/phoneme-24.mp3"),
	24 : preload("res://assets/audio/phoneme_sounds/phoneme-25.mp3"),
	25 : preload("res://assets/audio/phoneme_sounds/phoneme-26.mp3"),
	26 : preload("res://assets/audio/phoneme_sounds/phoneme-27.mp3"),
	27 : preload("res://assets/audio/phoneme_sounds/phoneme-28.mp3"),
	28 : preload("res://assets/audio/phoneme_sounds/phoneme-29.mp3"),
	29 : preload("res://assets/audio/phoneme_sounds/phoneme-30.mp3"),
	30 : preload("res://assets/audio/phoneme_sounds/phoneme-31.mp3"),
	31 : preload("res://assets/audio/phoneme_sounds/phoneme-32.mp3"),
	32 : preload("res://assets/audio/phoneme_sounds/phoneme-33.mp3"),
	33 : preload("res://assets/audio/phoneme_sounds/phoneme-34.mp3"),
	34 : preload("res://assets/audio/phoneme_sounds/phoneme-35.mp3"),
	35 : preload("res://assets/audio/phoneme_sounds/phoneme-36.mp3"),
	36 : preload("res://assets/audio/phoneme_sounds/phoneme-37.mp3"),
	37 : preload("res://assets/audio/phoneme_sounds/phoneme-38.mp3"),
	38 : preload("res://assets/audio/phoneme_sounds/phoneme-39.mp3"),
	39 : preload("res://assets/audio/phoneme_sounds/phoneme-40.mp3"),
	40 : preload("res://assets/audio/phoneme_sounds/phoneme-41.mp3"),
	41 : preload("res://assets/audio/phoneme_sounds/phoneme-42.mp3"),
	42 : preload("res://assets/audio/phoneme_sounds/phoneme-43.mp3"),
	43 : preload("res://assets/audio/phoneme_sounds/phoneme-44.mp3"),
}
# Holds the letter representations of the phonemes
var letter_lib : Dictionary[int,String] = {
	0 : "b, bb",
	1 : "d, dd, ed",
	2 : "f, ff, ph",
	3 : "g, gg, gue",
	4 : "h, wh",
	5 : "j, dge, g",
	6 : "k, c",
	7 : "l, ll",
	8 : "m, mm",
	9 : "n, kn",
	10 : "p, pp",
	11 : "r, wr",
	12 : "s, ss, c",
	13 : "t,tt",
	14 : "v,ve",
	15 : "w",
	16 : "z, zz",
	17 : "s, si, z",
	18 : "ch",
	19 : "sh",
	20 : "th",
	21 : "TH",
	22 : "ng, ngue",
	23 : "y",
	24 : "a",
	25 : "ay, eigh",
	26 : "eh",
	27 : "ee,y",
	28 : "ih",
	29 : "ai",
	30 : "aw",
	31 : "oh, eau",
	32 : "oo",
	33 : "euh",
	34 : "ooh",
	35 : "oi, oy",
	36 : "ow",
	37 : "uh",
	38 : "air, eir",
	39 : "ahr",
	40 : "ir, er",
	41 : "eur",
	42 : "ear, ier",
	43 : "ure, our",
}
# Holds the word examples of the phonemes
var word_lib : Dictionary[int,String] = {
	0 : "(B)one",
	1 : "(D)ouse",
	2 : "(F)old",
	3 : "(G)rave",
	4 : "(H)old",
	5 : "(J)ump",
	6 : "(C)lamp",
	7 : "(L)earn",
	8 : "(M)ouse",
	9 : "(KN)ow",
	10 : "(P)ress",
	11 : "(WR)ithe",
	12 : "(S)ound",
	13 : "(T)rial",
	14 : "(V)ery",
	15 : "(W)indy",
	16 : "fi(ZZ)",
	17 : "plea(S)ure",
	18 : "(CH)ase",
	19 : "(SH)ake",
	20 : "(TH)is",
	21 : "wrea(TH)",
	22 : "bri(NG)",
	23 : "(Y)ell",
	24 : "ch(A)t",
	25 : "p(AI)d",
	26 : "dr(E)ad",
	27 : "bl(EE)d",
	28 : "cl(I)p",
	29 : "cl(I)mb",
	30 : "d(AW)n",
	31 : "cr(OA)k",
	32 : "c(OO)k",
	33 : "cl(U)b",
	34 : "sh(OE)",
	35 : "empl(OY)",
	36 : "cl(OW)n",
	37 : "(A)bove",
	38 : "imp(AIR)",
	39 : "ch(A)rge",
	40 : "p(ER)fect",
	41 : "ch(ORE)",
	42 : "cl(EAR)",
	43 : "p(URE)",
}
var frame_lib : Dictionary[int,SpriteFrames] = {
	0 : preload("res://assets/sprite_frames/0-B.tres"),
	1 : preload("res://assets/sprite_frames/0-B.tres"),
	2 : preload("res://assets/sprite_frames/0-B.tres"),
	3 : preload("res://assets/sprite_frames/0-B.tres"),
	4 : preload("res://assets/sprite_frames/0-B.tres"),
	5 : preload("res://assets/sprite_frames/0-B.tres"),
	6 : preload("res://assets/sprite_frames/0-B.tres"),
	7 : preload("res://assets/sprite_frames/0-B.tres"),
	8 : preload("res://assets/sprite_frames/0-B.tres"),
	9 : preload("res://assets/sprite_frames/0-B.tres"),
	10 : preload("res://assets/sprite_frames/0-B.tres"),
	11 : preload("res://assets/sprite_frames/0-B.tres"),
	12 : preload("res://assets/sprite_frames/0-B.tres"),
	13 : preload("res://assets/sprite_frames/0-B.tres"),
	14 : preload("res://assets/sprite_frames/0-B.tres"),
	15 : preload("res://assets/sprite_frames/0-B.tres"),
	16 : preload("res://assets/sprite_frames/0-B.tres"),
	17 : preload("res://assets/sprite_frames/0-B.tres"),
	18 : preload("res://assets/sprite_frames/0-B.tres"),
	19 : preload("res://assets/sprite_frames/0-B.tres"),
	20 : preload("res://assets/sprite_frames/0-B.tres"),
	21 : preload("res://assets/sprite_frames/0-B.tres"),
	22 : preload("res://assets/sprite_frames/0-B.tres"),
	23 : preload("res://assets/sprite_frames/0-B.tres"),
	24 : preload("res://assets/sprite_frames/0-B.tres"),
	25 : preload("res://assets/sprite_frames/0-B.tres"),
	26 : preload("res://assets/sprite_frames/0-B.tres"),
	27 : preload("res://assets/sprite_frames/0-B.tres"),
	28 : preload("res://assets/sprite_frames/0-B.tres"),
	29 : preload("res://assets/sprite_frames/0-B.tres"),
	30 : preload("res://assets/sprite_frames/0-B.tres"),
	31 : preload("res://assets/sprite_frames/0-B.tres"),
	32 : preload("res://assets/sprite_frames/0-B.tres"),
	33 : preload("res://assets/sprite_frames/0-B.tres"),
	34 : preload("res://assets/sprite_frames/0-B.tres"),
	35 : preload("res://assets/sprite_frames/0-B.tres"),
	36 : preload("res://assets/sprite_frames/0-B.tres"),
	37 : preload("res://assets/sprite_frames/0-B.tres"),
	38 : preload("res://assets/sprite_frames/0-B.tres"),
	39 : preload("res://assets/sprite_frames/0-B.tres"),
	40 : preload("res://assets/sprite_frames/0-B.tres"),
	41 : preload("res://assets/sprite_frames/0-B.tres"),
	42 : preload("res://assets/sprite_frames/0-B.tres"),
	43 : preload("res://assets/sprite_frames/0-B.tres"),
}
